Implement options/commands for coprctl

diff --git a/coprctl/bin/coprctl b/coprctl/bin/coprctl
--- a/coprctl/bin/coprctl
+++ b/coprctl/bin/coprctl
@@ -2,6 +2,8 @@
 
 set -euo pipefail
 
+# Logging
+
 function log-debug {
   if [ -n "${DEBUG:-}" ]; then
     echo 'debug:' "$@"
@@ -24,13 +26,179 @@ function log-fatal {
   echo 'fatal:' "$@"
 }
 
+HELP_MAIN='coprctl uses copr-cli and yq to manage COPR resources using yaml, like Kubernetes.
+
+ Find more information at: https://github.com/jfhbrook/public/tree/main/coprctl
+
+Commands:
+  get             Display a resource
+  apply           Apply a configuration to a resource by file name or stdin
+
+Usage:
+  coprctl [flags] [options]
+
+Use "coprctl <command> --help" for more information about a given command.'
+
+function main {
+  COMMAND=""
+  TYPE=""
+
+  DRY_RUN="none"
+  FILENAME=""
+
+  local show_help=""
+
+  while [[ $# -gt 0 ]]; do
+    case ${1} in
+      --help)
+        show_help=1
+        shift
+        ;;
+      --dry-run)
+        if [[ "${2}" =~ ^(none|server|client)$ ]]; then
+          DRY_RUN="${2}"
+          shift
+          shift
+        else
+          log-error "--dry-run must be one of: none, server, client"
+          exit 1
+        fi
+        ;;
+      -f|--filename)
+        FILENAME="${2}"
+        shift
+        shift
+        ;;
+      -*)
+        log-error "unknown option: ${1}"
+        exit 1
+        ;;
+      *)
+        if [ -z "${COMMAND}" ]; then
+          COMMAND="${1}"
+          shift
+        elif [ -z "${TYPE}" ]; then
+          TYPE="${1}"
+          shift
+        else
+          log-error "unknown argument: ${1}"
+          exit 1
+        fi
+        ;;
+    esac
+  done
+
+  log-debug "command: ${COMMAND:-NULL}"
+  log-debug "type: ${TYPE:-NULL}"
+
+  case "${COMMAND}" in
+    get)
+      if [ -n "${show_help}" ]; then
+        echo "${HELP_GET}"
+        exit
+      fi
+      get
+      ;;
+    apply)
+      if [ -n "${show_help}" ]; then
+        echo "${HELP_APPLY}"
+        exit
+      fi
+
+      apply
+      ;;
+    api-resources)
+      if [ -n "${show_help}" ]; then
+        echo "${HELP_API_RESOURCES}"
+        exit
+      fi
+      api-resources
+      ;;
+    *)
+      if [ -n "${COMMAND}" ]; then
+        log-error "unknown command: ${COMMAND}"
+      fi
+      echo "${HELP_MAIN}"
+      exit 1
+      ;;
+  esac
+}
+
+# Get command
+
+HELP_GET='Display a resource.
+
+Prints a yaml representation of the selected resource, intended for easy insertion into a resources file. Currently very limited, but may be expanded to offer more kubectl-like capabilities in the future.
+
+Use "coprctl api-resources" for a complete list of supported resources.
+
+Examples:
+  # Show a pypi package called "python3-pyee"
+  coprctl get package-pypi python3-pyee
+
+Usage:
+  coprctl get TYPE NAME [flags] [options]'
+
+function get {
+  log-error "not implemented: get"
+  exit 1
+}
+
+# Apply command
+
+HELP_APPLY='Apply a configuration to a resource by file name or stdin. The resource name must be specified. This resource will be created if it doesn'"'"'t exist yet. To use '"'"'apply'"'"', always create the resource initially with either '"'"'apply'"'"' or '"'"'create --save-config'"'"'.
+
+ Formats understood by yq are accepted.
+
+Examples:
+  # Apply the configuration in copr.yaml
+  coprctl apply -f ./copr.json
+  
+Options:
+    --dry-run='"'"'none'"'"':
+	Must be "none", "server", or "client". If client strategy, only print the object that would be sent, without sending it. If server strategy, submit server-side request without persisting the resource.
+
+    -f, --filename=[]:
+	The file that contains the configurations to apply.
+
+Usage:
+  coprctl apply (-f FILENAME) [options]
+
+Use "coprctl <command> --help" for more information about a given command.'
+
+function apply {
+  # TODO: This won't clean up the tmpfile on exit. It's not a huge deal - the
+  # OS should clean it up on boots - but it's *improper*.
+  if [ -z "${FILENAME}" ]; then
+    FILENAME="$(mktemp)"
+    "${FILENAME}" < /dev/stdin
+  fi
+
+  # file, doc selector and argv set globally to avoid DI Hell. Luckily this
+  # is the only call site we have to be careful about.
+  yq --no-doc 'document_index' "${FILENAME}" | while read -r i; do
+    DOC='select(document_index == '"${i}"')'
+    ARGV=()
+
+    log-debug 'doc:' "${DOC}"
+
+    load-document
+
+    if [[ "${DRY_RUN}" != 'none' ]]; then
+      log-info 'dry-run:' copr-cli "${ARGV[@]}"
+    else
+      copr-cli "${ARGV[@]}"
+    fi
+  done
+}
+
 function load-property {
   local selector="${1}"
   local name="${2}"
 
   local value
 
-  value="$(yq "${DOC}"' | '"${selector}" "${FILE}")"
+  value="$(yq "${DOC}"' | '"${selector}" "${FILENAME}")"
 
   # TODO: Ideally I'd get yq to return a blank instead of the string "null".
   # Unfortunately, alternatives and doc filtering combined can have strange
@@ -44,12 +212,17 @@ function load-project {
   local name
   local action="modify"
 
-  name="$(yq "${DOC}"' | .metadata.name' "${FILE}")"
+  name="$(yq "${DOC}"' | .metadata.name' "${FILENAME}")"
 
-  log-debug "checking if project ${name} exists"
-  if ! copr-cli get "${name}" &> /dev/null; then
-    log-debug "project ${name} does not exist"
+  if [[ "${DRY_RUN}" == 'client' ]]; then
+    log-info 'dry-run:' copr-cli get "${name}"
     action="create"
+  else
+    log-debug "checking if project ${name} exists"
+    if ! copr-cli get "${name}" &> /dev/null; then
+      log-debug "project ${name} does not exist"
+      action="create"
+    fi
   fi
 
   ARGV+=("${action}" "${name}")
@@ -81,16 +254,21 @@ function load-package {
   local name
   local action
 
-  copr="$(yq "${DOC}"' | .spec.copr' "${FILE}")"
-  name="$(yq "${DOC}"' | .metadata.name' "${FILE}")"
+  copr="$(yq "${DOC}"' | .spec.copr' "${FILENAME}")"
+  name="$(yq "${DOC}"' | .metadata.name' "${FILENAME}")"
 
   action="edit-package-${type}"
 
-  # TODO: conditional might be backwards
-  log-debug "checking if package ${copr} --name ${name} exists"
-  if ! copr get-package "${copr}" --name "${name}" &> /dev/null; then
-    log-debug "package ${copr} --name ${name} does not exist"
+
+  if [[ "${DRY_RUN}" == 'client' ]]; then
+    log-info 'dry-run:' copr-cli get "${name}"
     action="add-package-${type}"
+  else
+    log-debug "checking if package ${copr} --name ${name} exists"
+    if ! copr get-package "${copr}" --name "${name}" &> /dev/null; then
+      log-debug "package ${copr} --name ${name} does not exist"
+      action="add-package-${type}"
+    fi
   fi
 
   ARGV+=("${action}" "${copr}" --name "${name}")
@@ -103,10 +281,10 @@ function load-document {
   local kind
   local apiVersion
 
-  kind="$(yq "${DOC}"' | .kind' "./${FILE}")"
+  kind="$(yq "${DOC}"' | .kind' "./${FILENAME}")"
 
   log-debug "kind: ${kind}"
-  apiVersion="$(yq "${DOC}"' | .apiVersion' "./${FILE}")"
+  apiVersion="$(yq "${DOC}"' | .apiVersion' "./${FILENAME}")"
 
   # because we're classy like that
   if [[ "${apiVersion}" != 'coprctl/v1alpha1' ]]; then
@@ -167,25 +345,10 @@ function load-document {
   esac
 }
 
-function apply {
-  yq --no-doc 'document_index' "${FILE}" | while read -r i; do
-    # Accessed globally by load-document and its delegates. It's not very
-    # explicit and you *could* hurt yourself if you don't reset ARGV before
-    # a call, but this avoids DI Hell and this is the only call site.
-    DOC='select(document_index == '"${i}"')'
-    ARGV=()
-
-    log-debug 'doc:' "${DOC}"
-
-    load-document
-
-    echo copr-cli "${ARGV[@]}"
-  done
+function api-resources {
+  log-error "unimplemented: api-resources"
+  exit 1
 }
 
-# TODO: implement arguments, "coprctl get" etc
-
-FILE='./test.yml'
-apply
-
-echo 'ok'
+# giddyup
+main "$@"
